# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4b55b2887a41417468e31e293fded3e499674bfd000429ac84b2998ce8ada2863fd4a42b7d3f38ab04e08b26415d6e6bde7545d9b60d65a7d50c7477e36003f

test:
  secret_key_base: ce15b736efc3a8918c35fb425d050c3e667972db5ef563116324fbf3dfada922d770b487e9f8d23ceb78b2f367222e6bed43b4158ad4523270b05389c50fa2da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
